#############################################################################
# Makefile for building: test
# Generated by qmake (3.0) (Qt 5.1.0) on: Thu 4. Jul 14:43:44 2013
# Project:  test.pro
# Template: app
# Command: c:\qt\5.1.0\5.1.0\msvc2012\bin\qmake.exe -o Makefile test.pro
#############################################################################

MAKEFILE      = Makefile

first: debug
install: debug-install
uninstall: debug-uninstall
QMAKE         = c:\qt\5.1.0\5.1.0\msvc2012\bin\qmake.exe
DEL_FILE      = del
CHK_DIR_EXISTS= if not exist
MKDIR         = mkdir
COPY          = copy /y
COPY_FILE     = $(COPY)
COPY_DIR      = xcopy /s /q /y /i
INSTALL_FILE  = $(COPY_FILE)
INSTALL_PROGRAM = $(COPY_FILE)
INSTALL_DIR   = $(COPY_DIR)
DEL_FILE      = del
SYMLINK       = copy /y
DEL_DIR       = rmdir
MOVE          = move
SUBTARGETS    =  \
		debug \
		release


debug: FORCE
	@set MAKEFLAGS=$(MAKEFLAGS)
	$(MAKE) -f $(MAKEFILE).Debug
debug-make_first: FORCE
	@set MAKEFLAGS=$(MAKEFLAGS)
	$(MAKE) -f $(MAKEFILE).Debug 
debug-all: FORCE
	@set MAKEFLAGS=$(MAKEFLAGS)
	$(MAKE) -f $(MAKEFILE).Debug all
debug-clean: FORCE
	@set MAKEFLAGS=$(MAKEFLAGS)
	$(MAKE) -f $(MAKEFILE).Debug clean
debug-distclean: FORCE
	@set MAKEFLAGS=$(MAKEFLAGS)
	$(MAKE) -f $(MAKEFILE).Debug distclean
debug-install: FORCE
	@set MAKEFLAGS=$(MAKEFLAGS)
	$(MAKE) -f $(MAKEFILE).Debug install
debug-uninstall: FORCE
	@set MAKEFLAGS=$(MAKEFLAGS)
	$(MAKE) -f $(MAKEFILE).Debug uninstall
release: FORCE
	@set MAKEFLAGS=$(MAKEFLAGS)
	$(MAKE) -f $(MAKEFILE).Release
release-make_first: FORCE
	@set MAKEFLAGS=$(MAKEFLAGS)
	$(MAKE) -f $(MAKEFILE).Release 
release-all: FORCE
	@set MAKEFLAGS=$(MAKEFLAGS)
	$(MAKE) -f $(MAKEFILE).Release all
release-clean: FORCE
	@set MAKEFLAGS=$(MAKEFLAGS)
	$(MAKE) -f $(MAKEFILE).Release clean
release-distclean: FORCE
	@set MAKEFLAGS=$(MAKEFLAGS)
	$(MAKE) -f $(MAKEFILE).Release distclean
release-install: FORCE
	@set MAKEFLAGS=$(MAKEFLAGS)
	$(MAKE) -f $(MAKEFILE).Release install
release-uninstall: FORCE
	@set MAKEFLAGS=$(MAKEFLAGS)
	$(MAKE) -f $(MAKEFILE).Release uninstall

Makefile: test.pro ..\..\..\..\qt\5.1.0\5.1.0\msvc2012\mkspecs\win32-msvc2012\qmake.conf ..\..\..\..\qt\5.1.0\5.1.0\msvc2012\mkspecs\features\spec_pre.prf \
		..\..\..\..\qt\5.1.0\5.1.0\msvc2012\mkspecs\common\shell-win32.conf \
		..\..\..\..\qt\5.1.0\5.1.0\msvc2012\mkspecs\qconfig.pri \
		..\..\..\..\qt\5.1.0\5.1.0\msvc2012\mkspecs\modules\qt_lib_axbase.pri \
		..\..\..\..\qt\5.1.0\5.1.0\msvc2012\mkspecs\modules\qt_lib_axcontainer.pri \
		..\..\..\..\qt\5.1.0\5.1.0\msvc2012\mkspecs\modules\qt_lib_axserver.pri \
		..\..\..\..\qt\5.1.0\5.1.0\msvc2012\mkspecs\modules\qt_lib_bootstrap.pri \
		..\..\..\..\qt\5.1.0\5.1.0\msvc2012\mkspecs\modules\qt_lib_clucene.pri \
		..\..\..\..\qt\5.1.0\5.1.0\msvc2012\mkspecs\modules\qt_lib_concurrent.pri \
		..\..\..\..\qt\5.1.0\5.1.0\msvc2012\mkspecs\modules\qt_lib_core.pri \
		..\..\..\..\qt\5.1.0\5.1.0\msvc2012\mkspecs\modules\qt_lib_declarative.pri \
		..\..\..\..\qt\5.1.0\5.1.0\msvc2012\mkspecs\modules\qt_lib_designer.pri \
		..\..\..\..\qt\5.1.0\5.1.0\msvc2012\mkspecs\modules\qt_lib_designercomponents.pri \
		..\..\..\..\qt\5.1.0\5.1.0\msvc2012\mkspecs\modules\qt_lib_gui.pri \
		..\..\..\..\qt\5.1.0\5.1.0\msvc2012\mkspecs\modules\qt_lib_help.pri \
		..\..\..\..\qt\5.1.0\5.1.0\msvc2012\mkspecs\modules\qt_lib_multimedia.pri \
		..\..\..\..\qt\5.1.0\5.1.0\msvc2012\mkspecs\modules\qt_lib_multimediawidgets.pri \
		..\..\..\..\qt\5.1.0\5.1.0\msvc2012\mkspecs\modules\qt_lib_network.pri \
		..\..\..\..\qt\5.1.0\5.1.0\msvc2012\mkspecs\modules\qt_lib_opengl.pri \
		..\..\..\..\qt\5.1.0\5.1.0\msvc2012\mkspecs\modules\qt_lib_openglextensions.pri \
		..\..\..\..\qt\5.1.0\5.1.0\msvc2012\mkspecs\modules\qt_lib_platformsupport.pri \
		..\..\..\..\qt\5.1.0\5.1.0\msvc2012\mkspecs\modules\qt_lib_printsupport.pri \
		..\..\..\..\qt\5.1.0\5.1.0\msvc2012\mkspecs\modules\qt_lib_qml.pri \
		..\..\..\..\qt\5.1.0\5.1.0\msvc2012\mkspecs\modules\qt_lib_qmldevtools.pri \
		..\..\..\..\qt\5.1.0\5.1.0\msvc2012\mkspecs\modules\qt_lib_qmltest.pri \
		..\..\..\..\qt\5.1.0\5.1.0\msvc2012\mkspecs\modules\qt_lib_qtmultimediaquicktools.pri \
		..\..\..\..\qt\5.1.0\5.1.0\msvc2012\mkspecs\modules\qt_lib_quick.pri \
		..\..\..\..\qt\5.1.0\5.1.0\msvc2012\mkspecs\modules\qt_lib_quickparticles.pri \
		..\..\..\..\qt\5.1.0\5.1.0\msvc2012\mkspecs\modules\qt_lib_script.pri \
		..\..\..\..\qt\5.1.0\5.1.0\msvc2012\mkspecs\modules\qt_lib_scripttools.pri \
		..\..\..\..\qt\5.1.0\5.1.0\msvc2012\mkspecs\modules\qt_lib_sensors.pri \
		..\..\..\..\qt\5.1.0\5.1.0\msvc2012\mkspecs\modules\qt_lib_serialport.pri \
		..\..\..\..\qt\5.1.0\5.1.0\msvc2012\mkspecs\modules\qt_lib_sql.pri \
		..\..\..\..\qt\5.1.0\5.1.0\msvc2012\mkspecs\modules\qt_lib_svg.pri \
		..\..\..\..\qt\5.1.0\5.1.0\msvc2012\mkspecs\modules\qt_lib_testlib.pri \
		..\..\..\..\qt\5.1.0\5.1.0\msvc2012\mkspecs\modules\qt_lib_uitools.pri \
		..\..\..\..\qt\5.1.0\5.1.0\msvc2012\mkspecs\modules\qt_lib_v8.pri \
		..\..\..\..\qt\5.1.0\5.1.0\msvc2012\mkspecs\modules\qt_lib_webkit.pri \
		..\..\..\..\qt\5.1.0\5.1.0\msvc2012\mkspecs\modules\qt_lib_webkitwidgets.pri \
		..\..\..\..\qt\5.1.0\5.1.0\msvc2012\mkspecs\modules\qt_lib_widgets.pri \
		..\..\..\..\qt\5.1.0\5.1.0\msvc2012\mkspecs\modules\qt_lib_xml.pri \
		..\..\..\..\qt\5.1.0\5.1.0\msvc2012\mkspecs\modules\qt_lib_xmlpatterns.pri \
		..\..\..\..\qt\5.1.0\5.1.0\msvc2012\mkspecs\features\qt_functions.prf \
		..\..\..\..\qt\5.1.0\5.1.0\msvc2012\mkspecs\features\qt_config.prf \
		..\..\..\..\qt\5.1.0\5.1.0\msvc2012\mkspecs\win32-msvc2012\qmake.conf \
		..\..\..\..\qt\5.1.0\5.1.0\msvc2012\mkspecs\features\spec_post.prf \
		..\..\..\..\qt\5.1.0\5.1.0\msvc2012\mkspecs\features\exclusive_builds.prf \
		..\..\..\..\qt\5.1.0\5.1.0\msvc2012\mkspecs\features\default_pre.prf \
		..\..\..\..\qt\5.1.0\5.1.0\msvc2012\mkspecs\features\win32\default_pre.prf \
		test.pri \
		..\..\..\..\qt\5.1.0\5.1.0\msvc2012\mkspecs\features\resolve_config.prf \
		..\..\..\..\qt\5.1.0\5.1.0\msvc2012\mkspecs\features\default_post.prf \
		..\..\..\..\qt\5.1.0\5.1.0\msvc2012\mkspecs\features\win32\rtti.prf \
		..\..\..\..\qt\5.1.0\5.1.0\msvc2012\mkspecs\features\warn_on.prf \
		..\..\..\..\qt\5.1.0\5.1.0\msvc2012\mkspecs\features\qt.prf \
		..\..\..\..\qt\5.1.0\5.1.0\msvc2012\mkspecs\features\resources.prf \
		..\..\..\..\qt\5.1.0\5.1.0\msvc2012\mkspecs\features\moc.prf \
		..\..\..\..\qt\5.1.0\5.1.0\msvc2012\mkspecs\features\win32\opengl.prf \
		..\..\..\..\qt\5.1.0\5.1.0\msvc2012\mkspecs\features\uic.prf \
		..\..\..\..\qt\5.1.0\5.1.0\msvc2012\mkspecs\features\win32\windows.prf \
		..\..\..\..\qt\5.1.0\5.1.0\msvc2012\mkspecs\features\testcase_targets.prf \
		..\..\..\..\qt\5.1.0\5.1.0\msvc2012\mkspecs\features\exceptions.prf \
		..\..\..\..\qt\5.1.0\5.1.0\msvc2012\mkspecs\features\yacc.prf \
		..\..\..\..\qt\5.1.0\5.1.0\msvc2012\mkspecs\features\lex.prf \
		test.pro \
		C:/qt/5.1.0/5.1.0/msvc2012/lib/Qt5Widgets.prl \
		C:/qt/5.1.0/5.1.0/msvc2012/lib/Qt5Gui.prl \
		C:/qt/5.1.0/5.1.0/msvc2012/lib/Qt5Core.prl \
		C:/qt/5.1.0/5.1.0/msvc2012/lib/libEGLd.prl \
		C:/qt/5.1.0/5.1.0/msvc2012/lib/libGLESv2d.prl
	$(QMAKE) -o Makefile test.pro
..\..\..\..\qt\5.1.0\5.1.0\msvc2012\mkspecs\features\spec_pre.prf:
..\..\..\..\qt\5.1.0\5.1.0\msvc2012\mkspecs\common\shell-win32.conf:
..\..\..\..\qt\5.1.0\5.1.0\msvc2012\mkspecs\qconfig.pri:
..\..\..\..\qt\5.1.0\5.1.0\msvc2012\mkspecs\modules\qt_lib_axbase.pri:
..\..\..\..\qt\5.1.0\5.1.0\msvc2012\mkspecs\modules\qt_lib_axcontainer.pri:
..\..\..\..\qt\5.1.0\5.1.0\msvc2012\mkspecs\modules\qt_lib_axserver.pri:
..\..\..\..\qt\5.1.0\5.1.0\msvc2012\mkspecs\modules\qt_lib_bootstrap.pri:
..\..\..\..\qt\5.1.0\5.1.0\msvc2012\mkspecs\modules\qt_lib_clucene.pri:
..\..\..\..\qt\5.1.0\5.1.0\msvc2012\mkspecs\modules\qt_lib_concurrent.pri:
..\..\..\..\qt\5.1.0\5.1.0\msvc2012\mkspecs\modules\qt_lib_core.pri:
..\..\..\..\qt\5.1.0\5.1.0\msvc2012\mkspecs\modules\qt_lib_declarative.pri:
..\..\..\..\qt\5.1.0\5.1.0\msvc2012\mkspecs\modules\qt_lib_designer.pri:
..\..\..\..\qt\5.1.0\5.1.0\msvc2012\mkspecs\modules\qt_lib_designercomponents.pri:
..\..\..\..\qt\5.1.0\5.1.0\msvc2012\mkspecs\modules\qt_lib_gui.pri:
..\..\..\..\qt\5.1.0\5.1.0\msvc2012\mkspecs\modules\qt_lib_help.pri:
..\..\..\..\qt\5.1.0\5.1.0\msvc2012\mkspecs\modules\qt_lib_multimedia.pri:
..\..\..\..\qt\5.1.0\5.1.0\msvc2012\mkspecs\modules\qt_lib_multimediawidgets.pri:
..\..\..\..\qt\5.1.0\5.1.0\msvc2012\mkspecs\modules\qt_lib_network.pri:
..\..\..\..\qt\5.1.0\5.1.0\msvc2012\mkspecs\modules\qt_lib_opengl.pri:
..\..\..\..\qt\5.1.0\5.1.0\msvc2012\mkspecs\modules\qt_lib_openglextensions.pri:
..\..\..\..\qt\5.1.0\5.1.0\msvc2012\mkspecs\modules\qt_lib_platformsupport.pri:
..\..\..\..\qt\5.1.0\5.1.0\msvc2012\mkspecs\modules\qt_lib_printsupport.pri:
..\..\..\..\qt\5.1.0\5.1.0\msvc2012\mkspecs\modules\qt_lib_qml.pri:
..\..\..\..\qt\5.1.0\5.1.0\msvc2012\mkspecs\modules\qt_lib_qmldevtools.pri:
..\..\..\..\qt\5.1.0\5.1.0\msvc2012\mkspecs\modules\qt_lib_qmltest.pri:
..\..\..\..\qt\5.1.0\5.1.0\msvc2012\mkspecs\modules\qt_lib_qtmultimediaquicktools.pri:
..\..\..\..\qt\5.1.0\5.1.0\msvc2012\mkspecs\modules\qt_lib_quick.pri:
..\..\..\..\qt\5.1.0\5.1.0\msvc2012\mkspecs\modules\qt_lib_quickparticles.pri:
..\..\..\..\qt\5.1.0\5.1.0\msvc2012\mkspecs\modules\qt_lib_script.pri:
..\..\..\..\qt\5.1.0\5.1.0\msvc2012\mkspecs\modules\qt_lib_scripttools.pri:
..\..\..\..\qt\5.1.0\5.1.0\msvc2012\mkspecs\modules\qt_lib_sensors.pri:
..\..\..\..\qt\5.1.0\5.1.0\msvc2012\mkspecs\modules\qt_lib_serialport.pri:
..\..\..\..\qt\5.1.0\5.1.0\msvc2012\mkspecs\modules\qt_lib_sql.pri:
..\..\..\..\qt\5.1.0\5.1.0\msvc2012\mkspecs\modules\qt_lib_svg.pri:
..\..\..\..\qt\5.1.0\5.1.0\msvc2012\mkspecs\modules\qt_lib_testlib.pri:
..\..\..\..\qt\5.1.0\5.1.0\msvc2012\mkspecs\modules\qt_lib_uitools.pri:
..\..\..\..\qt\5.1.0\5.1.0\msvc2012\mkspecs\modules\qt_lib_v8.pri:
..\..\..\..\qt\5.1.0\5.1.0\msvc2012\mkspecs\modules\qt_lib_webkit.pri:
..\..\..\..\qt\5.1.0\5.1.0\msvc2012\mkspecs\modules\qt_lib_webkitwidgets.pri:
..\..\..\..\qt\5.1.0\5.1.0\msvc2012\mkspecs\modules\qt_lib_widgets.pri:
..\..\..\..\qt\5.1.0\5.1.0\msvc2012\mkspecs\modules\qt_lib_xml.pri:
..\..\..\..\qt\5.1.0\5.1.0\msvc2012\mkspecs\modules\qt_lib_xmlpatterns.pri:
..\..\..\..\qt\5.1.0\5.1.0\msvc2012\mkspecs\features\qt_functions.prf:
..\..\..\..\qt\5.1.0\5.1.0\msvc2012\mkspecs\features\qt_config.prf:
..\..\..\..\qt\5.1.0\5.1.0\msvc2012\mkspecs\win32-msvc2012\qmake.conf:
..\..\..\..\qt\5.1.0\5.1.0\msvc2012\mkspecs\features\spec_post.prf:
..\..\..\..\qt\5.1.0\5.1.0\msvc2012\mkspecs\features\exclusive_builds.prf:
..\..\..\..\qt\5.1.0\5.1.0\msvc2012\mkspecs\features\default_pre.prf:
..\..\..\..\qt\5.1.0\5.1.0\msvc2012\mkspecs\features\win32\default_pre.prf:
test.pri:
..\..\..\..\qt\5.1.0\5.1.0\msvc2012\mkspecs\features\resolve_config.prf:
..\..\..\..\qt\5.1.0\5.1.0\msvc2012\mkspecs\features\default_post.prf:
..\..\..\..\qt\5.1.0\5.1.0\msvc2012\mkspecs\features\win32\rtti.prf:
..\..\..\..\qt\5.1.0\5.1.0\msvc2012\mkspecs\features\warn_on.prf:
..\..\..\..\qt\5.1.0\5.1.0\msvc2012\mkspecs\features\qt.prf:
..\..\..\..\qt\5.1.0\5.1.0\msvc2012\mkspecs\features\resources.prf:
..\..\..\..\qt\5.1.0\5.1.0\msvc2012\mkspecs\features\moc.prf:
..\..\..\..\qt\5.1.0\5.1.0\msvc2012\mkspecs\features\win32\opengl.prf:
..\..\..\..\qt\5.1.0\5.1.0\msvc2012\mkspecs\features\uic.prf:
..\..\..\..\qt\5.1.0\5.1.0\msvc2012\mkspecs\features\win32\windows.prf:
..\..\..\..\qt\5.1.0\5.1.0\msvc2012\mkspecs\features\testcase_targets.prf:
..\..\..\..\qt\5.1.0\5.1.0\msvc2012\mkspecs\features\exceptions.prf:
..\..\..\..\qt\5.1.0\5.1.0\msvc2012\mkspecs\features\yacc.prf:
..\..\..\..\qt\5.1.0\5.1.0\msvc2012\mkspecs\features\lex.prf:
test.pro:
C:/qt/5.1.0/5.1.0/msvc2012/lib/Qt5Widgets.prl:
C:/qt/5.1.0/5.1.0/msvc2012/lib/Qt5Gui.prl:
C:/qt/5.1.0/5.1.0/msvc2012/lib/Qt5Core.prl:
C:/qt/5.1.0/5.1.0/msvc2012/lib/libEGLd.prl:
C:/qt/5.1.0/5.1.0/msvc2012/lib/libGLESv2d.prl:
qmake: FORCE
	@$(QMAKE) -o Makefile test.pro

qmake_all: FORCE

make_first: debug-make_first release-make_first FORCE
all: debug-all release-all FORCE
clean: debug-clean release-clean FORCE
	-$(DEL_FILE) Win32\Debug\test.exp
	-$(DEL_FILE) Win32\Debug\test.ilk
	-$(DEL_FILE) vc*.pdb
	-$(DEL_FILE) vc*.idb
distclean: debug-distclean release-distclean FORCE
	-$(DEL_FILE) Makefile
	-$(DEL_FILE) Win32\Debug\test.pdb

debug-mocclean:
	@set MAKEFLAGS=$(MAKEFLAGS)
	$(MAKE) -f $(MAKEFILE).Debug mocclean
release-mocclean:
	@set MAKEFLAGS=$(MAKEFLAGS)
	$(MAKE) -f $(MAKEFILE).Release mocclean
mocclean: debug-mocclean release-mocclean

debug-mocables:
	@set MAKEFLAGS=$(MAKEFLAGS)
	$(MAKE) -f $(MAKEFILE).Debug mocables
release-mocables:
	@set MAKEFLAGS=$(MAKEFLAGS)
	$(MAKE) -f $(MAKEFILE).Release mocables
mocables: debug-mocables release-mocables

check: first
FORCE:

$(MAKEFILE).Debug: Makefile
$(MAKEFILE).Release: Makefile
